2_3:
	g++ -o 2_3 2_3.cpp

clean:
	rm -rf *.o 2_3

run:
	./2_3 $(n) 

run_opt: 
	mpirun -host creek04,creek04,creek04,creek04,creek04,creek04,creek04,creek04,creek05,creek05,creek05,creek05 -np $(proc) ./2_1 $(msg) $(v) 

